Status/urls.py
from django.urls import path
from .views import *


app_name = 'status'
urlpatterns = [
    path('shoptatus/', view_status, name='status')
]

Users/urls.py
from django.urls import path
from .views import *


app_name = 'users'
urlpatterns = [
    path('', login, name='login'),
    path('createUser/', create_user, name='createUser'),
    path('getUsers/', get_users, name='getUsers'),
    path('home/', dashboard, name='home'),
    path('addItem/', add_item, name='addItem'),
    path('addStock/', add_stock, name='addStock'),
    path('addSale/', add_sale, name='addSale'),
    path('expenditure/', expenditure, name='expenditure'),
    path('shopStatus/', view_status, name='shopStatus'),
    path('st/', init_status, name='st'),
]

myShop/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Users.urls'), namespace='users')),
]

Items/models.py
from django.db import models

# Create your models here.

Sales/models.py
from django.db import models

# Create your models here.

Status/models.py
from django.db import models

class Status(models.Model):
    available_cash = models.IntegerField(default = 0)
    stock_amount = models.IntegerField(default = 0)
    weight = models.IntegerField(default = 0)
    profits = models.IntegerField(default = 0)
    development = models.IntegerField(default = 0)

Stock/models.py
from django.db import models

# Create your models here.

Users/models.py
from django.db import models

class Users(models.Model):
    username = models.CharField(max_length = 100, unique=True)
    email = models.CharField(max_length = 100)
    password = models.CharField(max_length = 100)



class ItemList(models.Model):
    item = models.CharField(max_length=20, unique=True)


class StockHistory(models.Model):
    date = models.DateField(auto_now_add=True)
    item = models.CharField(max_length=100)
    qty = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)
    total_buying_price = models.IntegerField()
    buying_price_each = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)
    selling_price_each = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)
    profits_each = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)
    total_selling_price = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)
    total_profits = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)

class AvailableStock(models.Model):
    item = models.CharField(max_length=100, unique=True)
    qty = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)
    buying_price_each = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)
    selling_price_each = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)
    profits_each = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)


class Sales(models.Model):
    date = models.DateField(auto_now_add=True)
    item = models.CharField(max_length = 100)
    quantity = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)
    amount = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)
    profits = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)
    

class Status(models.Model):
    available_cash = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)
    stock_amount = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)
    weight = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)#cash+stock
    profits = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)#cash(updated after sale)
    development = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)#since first date of system use

class Expenditure(models.Model):
    date = models.DateField(auto_now_add=True)
    amount = models.IntegerField()
    reason = models.CharField(max_length = 100)

Items/views.py
from django.shortcuts import render

# Create your views here.

Sales/views.py
from django.shortcuts import render

# Create your views here.

Status/views.py
from django.shortcuts import render
from .models import Status

def view_status(request):
    #status = Status.objects.filter(id=1).first()
    return render(request, 'status.html')

Stock/views.py
from django.shortcuts import render

# Create your views here.

Users/views.py
from django.shortcuts import render, redirect
from decimal import Decimal
from .models import *
from django.http import HttpResponse
from Users.logic.stock import StockManager
from Users.logic.sales import SalesManager
from Users.logic.expenditure import ExpenditureManager


def create_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')

        Users.objects.create(username=username, email=email, password=password)
        print('\n\nuser created =>', username, email, password,'\n\n')
        return redirect('users:home')
    return render(request, 'create_user.html')


def get_users(request):
    users = Users.objects.all()
    for user in users:
        print('\n',user.username, user.email, user.password,'\n')
    return HttpResponse(users)


def login(request):
    if request.method == 'POST':
        uname = request.POST.get('username')
        password = request.POST.get('password')
        user = Users.objects.filter(username = uname).first()
        if user != None:
            if user.password == password:
                print('\n\n user ==> ',user.username, user.password)
                return redirect('users:home')
            return render(request, 'login.html',{'msg':'Invalid credentials'})
        return render(request, 'login.html',{'msg':'Invalid credentials'})
    return render(request, 'login.html')


def dashboard(request):
    status = Status.objects.get(id = 1)
    items = ItemList.objects.all()
    sales = Sales.objects.all()
    stock = AvailableStock.objects.all()
    hist = StockHistory.objects.all()
    exp = Expenditure.objects.all()
    data = {
        'status':status,
        'items':items,
        'sales':sales,
        'stock':stock,
        'history': hist,
        'expenditures':exp,
    }
    for item in items:
        print('\n', item.item)
    
    return render(request, 'dashboard.html',data)


def add_item(request):
    if request.method == 'POST':
        item = request.POST.get('item')
        add_item = StockManager()
        try:
            add_item.register_item(item)
        except Exception as e:
            return HttpResponse(e)
        return redirect('users:home')
    return redirect('users:home')


def add_stock(request):
    if request.method == 'POST':
        item = request.POST.get('item')
        qty = float(request.POST.get('qty'))
        total_buying_price = Decimal(request.POST.get('total_buying_price'))
        selling_price_each = Decimal(request.POST.get('selling_price_each'))
        source = request.POST.get('source')

        stock = StockManager()
        stock.new_stock(item, qty, total_buying_price, selling_price_each, source)
        return redirect('users:home')
    return redirect('users:home')


def add_sale(request):
    if request.method == 'POST':
        item = request.POST.get('item')
        quantity = float(request.POST.get('quantity'))

        sales = SalesManager()
        sales.add_sale(item, quantity)
        return redirect('users:home')
    return redirect('users:home')


def expenditure(request):
    if request.method == 'POST':
        amount = Decimal(request.POST.get('amount'))
        reason = request.POST.get('reason')

        exp = ExpenditureManager()
        exp.expend(amount, reason)
        return redirect('users:home')
    return redirect('users:home')


def view_status(request):
    status = Status.objects.filter(id=1).first()
    return render(request, 'status.html', {'status':status})

def init_status(request):
        Status.objects.create(available_cash=0, stock_amount=0, weight=0, profits=0, development=0)
        st = Status.objects.filter(id=1)
        #st = Status.objects.all()
        for s in st:
            print(s.development)
            return HttpResponse(s.development)
        return HttpResponse(st)

Status/templates/status.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Status</title>
</head>
<body>
    status
</body>
</html>

Users/templates/create_user.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create User</title>
    <link rel="stylesheet" href="../static/Users/css/create_user.css" />
    <style>
        body {
            font-family: Arial;
            background-color: whitesmoke;
            display: block;
            margin: 0 auto;
        }

        .content {
            width: 100vw;
            height: 100vh;
            text-align: center;
            display: block;
            margin: 0 auto;

        }

        h1 {
            margin-top: 10%;
        }

        .form {
            background-color: white;
            padding: 20px;
            width: 50%;
            display: block;
            margin: 0 auto;
            border-radius: 10px;
        }

        label {
            font-weight: bold;
        }

        input {
            margin: 10px;
            font-size: 20px;
            border-color: blue;
            border-radius: 5px;
        }

        button {
            border: none;
            border-radius: 5px;
            background-color: blue;
            color: white;
            font-weight: bold;
            padding-top: 3px;
            padding-bottom: 3px;
            padding-left: 10px;
            padding-right: 10px;
        }

        button:hover {
            background-color: green;
            color: white;
            padding-left: 10px;
            padding-right: 10px;
            cursor: pointer;
        }

        a {
            text-decoration: none;
            font-weight: bold;
            cursor: pointer;
        }
    </style>
</head>

<body>
    <div class='content'>
        <h1>CREATE USER</h1>
        <div class="form">
            <form method="post" action="{% url 'users:createUser' %}">
                {% csrf_token %}
                <label for="username">
                    username<br />
                    <input type="text" name="username">
                </label><br />
                <label for="email">
                    Email<br />
                    <input type="email" name="email">
                </label><br />
                <label for="password">
                    password<br />
                    <input type="password" name="password">
                </label><br />
                <button type="submit">Create</button>
            </form>
        </div>


        <p>
            Already have user account, <a href="{% url 'users:login' %}">Login</a>
        </p>
    </div>
</body>

</html>

Users/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="../static/Users/css/login.css" />
    <style>
        body {
            font-family: Arial;
            background-color: whitesmoke;
            display: block;
            margin: 0 auto;
        }

        .content {
            width: 100vw;
            height: 100vh;
            text-align: center;
            display: block;
            margin: 0 auto;

        }

        h1 {
            margin-top: 10%;
        }

        .form {
            background-color: white;
            padding: 20px;
            width: 50%;
            display: block;
            margin: 0 auto;
            border-radius: 10px;
        }

        label {
            font-weight: bold;
        }

        input {
            margin: 10px;
            font-size: 20px;
            border-color: blue;
            border-radius: 5px;
        }

        button {
            border: none;
            border-radius: 5px;
            background-color: blue;
            color: white;
            font-weight: bold;
            padding-top: 3px;
            padding-bottom: 3px;
            padding-left: 10px;
            padding-right: 10px;
        }

        button:hover {
            background-color: green;
            color: white;
            padding-left: 10px;
            padding-right: 10px;
            cursor: pointer;
        }

        a {
            text-decoration: none;
            font-weight: bold;
            cursor: pointer;
        }
    </style>
</head>

<body>
    <div class='content'>
        <h1>Login</h1>
        <p style="color: red; font-size: 10px;">{{msg}}</p>
        <div class="form">
            <form method="post" action="{% url 'users:login' %}">
                {% csrf_token %}
                <label for="username">
                    username<br />
                    <input type="text" name="username">
                </label><br />
                <label for="password">
                    password<br />
                    <input type="password" name="password">
                </label><br />
                <button type="submit">Login</button>
            </form>
        </div>


        <p>
            Don't have user account, <a href="{% url 'users:createUser' %}">Create</a>
        </p>
    </div>
</body>

</html>

Users/templates/status.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>status</title>
    <link rel="stylesheet" href="./../static/Users/css/status.css" />
</head>
<body>
    <div class="content">
        <h1><button class="back-button"> < </button>BUSINESS STATUS</h1>
        <div class="status-table">
            <table>
                <tbody>
                    <tr>
                        <th>CASH AMOUNT</th>
                        <th>STOCK AMOUNT</th>
                        <th>BUSINESS WEIGHT</th>
                        <th>PROFITS</th>
                        <th>DEVELOPMENT</th>
                    </tr>
                    <tr>
                        <td>{{status.available_cash}}</td>
                        <td>{{status.stock_amount}}</td>
                        <td>{{status.weight}}</td>
                        <td>{{status.profits}}</td>
                        <td>{{status.development}}</td>
                    </tr>
                </tbody>
            </table>
            <p>This status is based on the initial day of systemuse</p>
        </div>
    </div>
</body>
</html>